function conditie_Ic1()

fig=figure('Name','Conexiunea CA',...
            'Units','normalized',...
            'Position',[0.1 0.1 0.5 0.5],...
            'NumberTitle','off','color','#b593b0');
        
  Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.45 0.9 0.5],...
 'Fontsize',20,...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'String','Valorile introduse sunt gresite');    

Bp=uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.05 0.85 0.16 0.05],...
 'String','Back',...
 'Callback','close;start_interfata()');
        
end