function [Rb1,Rb2,Vcc,beta,Vbe,Re]=interfata(Rb1,Rb2,Vcc,beta,Vbe,Re)
fig=figure('Name','Conexiunea CA',...
            'Units','normalized',...
            'Position',[0.1 0.1 0.5 0.5],...
            'NumberTitle','off','color','#b593b0');
          ah=axes('unit','normalized','position',[0 0 1 1 ]);
bg=imread('temaAIA.jpg');O=imresize(bg,3);imagesc(O);
set(ah,'handlevisibility','off','visible','off')
uistack(ah, 'bottom'); 
        
pos=[0.5,0.1,0.4,0.4];
subplot('Position',pos);
x=imread('Schema de semnal mic.png');
image(x);
axis off;

pos1=[0.02,0.1,0.4,0.4];
subplot('Position',pos1);
y=imread('Curent alternativ.png');
image(y);
axis off;



 Vth=(Rb2/(Rb1+Rb2))*Vcc;
 Rth=(Rb1*Rb2)./(Rb1+Rb2);
 Ib=(Vth-Vbe)./(Rth+(beta+1)*Re);
 Ic=beta*Ib;
 Vce=Vcc-(beta+1)*Ib*Re; 
 gm=40*Ic;
 Av=gm*Re./(1+gm*Re); %aprox 1
 rbe=beta./gm;
 R0=Re.*(1./gm)/(Re+1./gm); %Re si (1/gm) sunt in paralel
 Ri=Re.*(rbe+(beta+1)*Re)./(Rth+rbe+(beta+1)*Re); % sunt in paralel

 
 grup1=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Date de iesire',...
 'FontSize',20,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.01 0.65 0.2 0.3]); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.7 0.25 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','gm = ',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.5834 0.25 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','Av = ',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.4666 0.25 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','rbe = ',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.35 0.25 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','R0 = ',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.2333 0.25 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','Ri = ',...
 'parent',grup1); 

 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.375 0.825 0.2 0.07],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',gm,...
         'parent',grup1);
 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.375 0.7 0.2 0.08],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Av,...
         'parent',grup1);
  b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.375 0.59 0.2 0.08],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',rbe,...
         'parent',grup1);
      b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.375 0.475 0.2 0.08],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',R0,...
         'parent',grup1);
      b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.375 0.35 0.2 0.08],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Ri,...
         'parent',grup1);
     
     

     
     
     
     
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.135 0.38 0.022 0.02],...
         'backgroundcolor', 'black',...
         'foregroundcolor','yellow',...
         'string',Rb1);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.18 0.208 0.022 0.02],...
         'backgroundcolor', 'black',...
         'foregroundcolor','yellow',...
         'string',Rb2);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.295 0.212 0.022 0.02],...
         'backgroundcolor', 'black',...
         'foregroundcolor','yellow',...
         'string',Re);
     
     
     
     
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.649 0.395 0.022 0.02],...
         'backgroundcolor', 'black',...
         'foregroundcolor','yellow',...
         'string',Rth);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.715 0.347 0.022 0.02],...
         'backgroundcolor', 'black',...
         'foregroundcolor','yellow',...
         'string',rbe);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.737 0.2 0.022 0.02],...
         'backgroundcolor', 'black',...
         'foregroundcolor','yellow',...
         'string',Re);
          
     
end