function interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) 

fig=figure('Name','Conexiunea CC',...
            'Units','normalized',...
            'Position',[0 0 1 1],...
            'NumberTitle','off','color','r');
        
       ah=axes('unit','normalized','position',[0 0 1 1 ]); %This creates the 'background' axes
bg=imread('temaAIA.jpg');O=imresize(bg,3);imagesc(O); %The imagesc function scales image data to the full range of the current colormap and displays the image. 
set(ah,'handlevisibility','off','visible','off') % Turn the handlevisibility off so that we don't inadvertently plot into the axes again % Also, make the axes invisible
uistack(ah, 'bottom'); % setam imaginea de fundal a interfetei

        
  grup1=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Date de intrare',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.01 0.69 0.1 0.3]);  

        
   Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.725 0.4 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Rb1[ohm]',...
 'parent',grup1); 
   Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.575 0.4 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Rb2[ohm]',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.425 0.4 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Vcc[V]',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.275 0.4 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Beta',...
 'parent',grup1); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.125 0.4 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Re[ohm]',...
 'parent',grup1); 
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.8 0.25 0.15],...
 'foregroundcolor','black',...
 'String',Rb1,...
 'parent',grup1,...
 'Callback','Rb1=round(str2num(get(gco,''String'')));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) '); %round(X) rounds each element of X to the nearest integer.
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.65 0.25 0.15],...
 'foregroundcolor','black',...
 'String',Rb2,...
 'parent',grup1,... 
'Callback','Rb2=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.5 0.25 0.15],...
 'foregroundcolor','black',...
 'String',Vcc,...
 'parent',grup1,...
 'Callback','Vcc=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
    Be= uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.5 0.38 0.25 0.08],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',beta,...
         'parent',grup1);

 
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.2 0.25 0.15],...
 'foregroundcolor','black',...
 'String',Re,...
 'parent',grup1,...
 'Callback','Re=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');

grup3=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Semnal',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.12 0.79 0.1 0.2]);
if(tip==0)
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.75 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','A = ',...
 'Enable', 'off',...%'off' – The user interface control is not operational and appears grayed-out.
 'parent',grup3);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.55 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','f = ',...
 'Enable', 'off',...
 'parent',grup3);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.15 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','N = ',...
 'Enable', 'off',...
 'parent',grup3);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.15 0.2 0.2],...
 'foregroundcolor','black',...
 'String',N,...
 'Enable', 'off',...
 'parent',grup3,...
 'Callback','N=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.75 0.2 0.2],...
 'foregroundcolor','black',...
 'String',A,...
 'Enable', 'off',...
 'parent',grup3,...
 'Callback','A=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.55 0.2 0.2],...
 'foregroundcolor','black',...
 'String',f,...
 'Enable', 'off',...
 'parent',grup3,...
 'Callback','f=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
elseif(tip==1)
    Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.75 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','A = ',...
 'parent',grup3);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.55 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','f = ',...
 'parent',grup3);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.15 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','N = ',...
 'parent',grup3);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.15 0.2 0.2],...
 'foregroundcolor','black',...
 'String',N,...
 'parent',grup3,...
 'Callback','N=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.75 0.2 0.2],...
 'foregroundcolor','black',...
 'String',A,...
 'parent',grup3,...
 'Callback','A=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.55 0.2 0.2],...
 'foregroundcolor','black',...
 'String',f,...
 'parent',grup3,...
 'Callback','f=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
    
end
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.35 0.2 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','C = ',...
 'parent',grup3);


Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.35 0.2 0.2],...
 'foregroundcolor','black',...
 'String',C,...
 'parent',grup3,...
 'Callback','C=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');


 grup2=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Tip Circuit',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.01 0.58 0.1 0.1029]); 

radioA=uicontrol('Style','Radiobutton',...
    'Units','Normalized',...
    'Position',[0.05,0.60,0.9,0.3],...
    'backgroundcolor','#b593b0',...
    'FontSize',9,...
    'value',tip,...
    'String','Curent Continuu',...
    'Callback','tip=get(gco,''value'');close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,0,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ',...
    'Parent', grup2); 
radioB=uicontrol('Style','Radiobutton',...
    'Units','Normalized',...
    'Position',[0.05,0.20,0.9,0.3],...
    'backgroundcolor','#b593b0',...
    'FontSize',9,...
    'value',tip,...
    'String','Curent alternativ',...
    'Callback','tip=get(gco,''value'');close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,1,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2);curentalternativ(Rb1,Rb2,Vcc,beta,Vbe,Re)',...
    'Parent', grup2); 

        
        
 Vth=(Rb2/(Rb1+Rb2))*Vcc;
 Rth=(Rb1*Rb2)./(Rb1+Rb2);
 Ib=(Vth-Vbe)./(Rth+(beta+1)*Re);  % !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 Ic=beta*Ib;
 Ie=(beta+1)*Ib;
 Vce=Vcc-(beta+1)*Ib*Re; %beta+1* ib este defapt ie iar Ie*Re este Ve
 gm=40*Ic;
 Av=gm*Re./(1+gm*Re); % care este aproximativ 1
 rbe=beta./gm;



 
 grup4=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Valori calculate ',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.23 0.6874 0.1 0.3]); 

Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.725 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Vth[V]',...
 'parent',grup4); 
   Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.575 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Rth[ohm]',...
 'parent',grup4); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.425 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Ib[A]',...
 'parent',grup4); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.275 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Ic[A]',...
 'parent',grup4); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.125 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Vce[V]',...
 'parent',grup4);


 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.52 0.85 0.25 0.07],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Vth,...
         'parent',grup4);
 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.52 0.7 0.25 0.07],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Rth,...
         'parent',grup4);
 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.517 0.55 0.39 0.11],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Ib,...
         'parent',grup4);
 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.5 0.4 0.27 0.07],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Ic,...
         'parent',grup4);
 b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.52 0.25 0.25 0.07],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Vce,...
         'parent',grup4);
 
     
 grup6=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Parametrii tranzistor',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.12 0.5759 0.1 0.2]);

b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.6 0.725 0.15 0.1],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',Vbe,... %0,7V 
         'parent',grup6);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.6 0.575 0.15 0.1],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',VceSAT,... %0.2V
         'parent',grup6);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.6 0.425 0.15 0.1],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',VceMAX,... % 45V
         'parent',grup6);
     b64 = uicontrol('style','text',...
         'units','Normalized',...
         'position',[0.6 0.275 0.15 0.1],...
         'backgroundcolor', 'white',...
         'foregroundcolor','black',...
         'string',IcMAX,...
         'parent',grup6);

     Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.65 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','Vbe[V]',...
 'parent',grup6); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.5 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','VceSAT[V]',...
 'parent',grup6); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.35 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','VceMAX[V]',...
 'parent',grup6); 
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.2 0.5 0.2],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',10,...
 'String','IcMAX[A]',...
 'parent',grup6); 

   

Si = uicontrol('style','PopupMenu',...
    'units','normalized',...
                 'position',[0.011 0.51 0.319 0.06],...
                 'fontsize',12,...
                 'backgroundcolor','#b593b0',...
                 'foregroundcolor','black',...
                 'fontweight','bold',... 
                 'string',{'dreptunghi';'triunghi';'sinus'},...
                 'value',tip_semnal,...
                 'Callback','tip_semnal=get(gco,''value'');close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
                  
 T=1/f; 
 t=0:T/100:N*T;
 


grup5=uibuttongroup('Visible','on',...
 'BackgroundColor','#b593b0',...
'ForegroundColor','black',...
 'Title','Condensatoare',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.23 0.58 0.1 0.1]); 

Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.65 0.25 0.3],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',9,...
 'String','C1[F]',...
 'parent',grup5);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.2 0.25 0.3],...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'FontSize',9,...
 'String','C2[F]',...
 'parent',grup5);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.65 0.4 0.25],...
 'foregroundcolor','black',...
 'String',C1,...
 'parent',grup5,...
 'Callback','C1=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.2 0.4 0.25],...
 'foregroundcolor','black',...
 'String',C2,...
 'parent',grup5,...
 'Callback','C2=str2num(get(gco,''String''));close;interfata(A,f,C,Rb1,Rb2,Vcc,beta,Vbe,Re,N,tip,tip_semnal,VceSAT,VceMAX,IcMAX,C1,C2) ');


 if(tip==0)
    
    vi=C;
 else
    switch(tip_semnal)
          case 1
              vi=C+A*sign(cos(2*pi*f*t)); %dreptunghi
          case 2
              vi=C+2*A/pi*acos(cos(2*pi*f*t))-A; %triunghi
          case 3
              vi=C+A*cos(2*pi*f*t); %sinus
              
 end
end
  subplot('Position',[0.0498 0.15 0.24 0.22]);
 
 %Reprezentare Vin
 if(tip==1)
    plot (t, vi);
    title('Tensiunea de intrare');
 xlabel('T[ms]');
 ylabel('Amplitudine');
 grid on; 
 else
     plot (t, vi, '.r');
     title('Tensiunea de intrare');
 xlabel('T[ms]');
 ylabel('Amplitudine');
 grid on; 
 end
 
 
 vo=Av*vi;
 
 nt=length(t);
 
%  Limitare semnal iesire + Semnale curent continuu/alternativ
 if(tip==1)
 for k=1:1:nt
     if (vo(k)>Vcc)
         vo(k)=Vcc;
     
     
     elseif(vo(k)<=(-Vcc))
             vo(k)=(-Vcc);
     end
               
 end
 
 else
     if(vo>=Vcc)
         vo=Vcc;
 end
 
 end
     
%      %Reprezentare Vout

  subplot('Position',[0.35 0.15 0.24 0.22]);  
 
     if(tip==1)

plot(t, vo,'b');
title('Tensiunea de iesire');
xlabel('T[ms]');
ylabel('Amplitudine');
grid on;
     else
     
    plot(t, vo, '.r');
    title('Tensiunea de iesire');
xlabel('T[ms]');
ylabel('Amplitudine');
grid on;
     end
     
if(tip==0)
    set(Si,'Visible','off');
end
pos = [0.37 0.59 0.3 0.4]; 
subplot('Position',pos);
x=imread('Colector comun.png');
image(x);
axis off;
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.426 0.53 0.2 0.05],...
 'Fontsize',18,...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'String','Colector Comun ');


pos1 = [0.686 0.59 0.3 0.4]; 
subplot('Position',pos1);
y=imread('Curent continuu.png');
image(y);
axis off;
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.742 0.53 0.2 0.05],...
 'Fontsize',18,...
 'backgroundcolor','#b593b0',...
 'foregroundcolor','black',...
 'String','Curent Continuu');



%-----------------------------PSF------------------------------%
Vce_psf = [0 0.05 0.10 0.15 0.20 0.30 0.50 1.00 5.00 10.00 12.00];
Ib1 = 20e-6; 
Ic1 = (10^(-3)) * [0 0.10 0.50 1.00 3.00 3.20 3.25 3.35 3.40 3.45  3.50];
Ib2 = 40e-6; 
Ic2 = (10^(-3)) * [0 0.10 0.50 1.50 7.00 7.20 7.25 7.35 7.40 7.45  7.50]; 
Ib3 = 60e-6;
Ic3 = (10^(-3)) * [0 0.10 0.50 2.00 11.00 11.20 11.25 11.35 11.40 11.45  11.50]; 
Ib4 = 80e-6;
Ic4 = (10^(-3)) * [0 0.10 0.50 2.50 15.00 15.20 15.25 15.35 15.40 15.45  15.50]; 
Ib5 = 100e-6;
Ic5 = (10^(-3)) * [0 0.10 0.50 3.00 19.00 19.20 19.25 19.35 19.40 19.45  19.50]; 


    subplot('Position',[0.65 0.127 0.33461 0.34])
    plot(Vce, Ic, 'h', 'MarkerSize', 5);
    hold on;
    plot([Vce,Vce,0],[0,Ic,Ic], 'b:');
    title('Punct static de functionare');
    xlabel('Vce[V]');
    ylabel('Ic[A]');
    grid on;
    hold on;
    plot([0,Vcc],[Vcc/Re,0],'r');% linia de pe grafic
    hold on;
    plot(Vce_psf, Ic1, 'black');
    plot(Vce_psf, Ic2, 'blue');
    plot(Vce_psf, Ic3, 'red');
    plot(Vce_psf, Ic4, 'yellow');
    plot(Vce_psf, Ic5, 'green');
    hold on;
    
    plot(Vce_psf, Ic1, 'bo');
    grid on;
    hold on;

    plot(Vce_psf, Ic2, 'bo');
    grid on;
    hold on;
    
    plot(Vce_psf, Ic3, 'bo');
    grid on;
    hold on;
    
    plot(Vce_psf, Ic4, 'bo');
    grid on;
    hold on;
    
    plot(Vce_psf, Ic5, 'bo');
    grid on;
    hold on;
    
    
 %-----------------------------------------------------------%

     
     if(Ic>IcMAX)
    conditie_Ic1();

     else
         if(Ic<0.001)
    conditie_Ic1(); 
         else if(Vce>VceMAX)
                 conditie_Ic1();
             end
end
 
 
end