Fig=figure('Name','PROIECT',...
           'color', [0 0.55 0.3],...
           'Units','normalized',...
           'Position',[0 0 1 1]);
       
   x=imread('design2.jpg');
     image(x);
     set(gca,'Position',[0 0 1 1]);
                
                
                
   f=uimenu('Label','Proiect');
   uimenu(f,'Label','Pagina principala','Callback','start1');
   uimenu(f,'Label','Documentatie','Callback','open(''documentatie.doc'')');
   uimenu(f,'Label','Prezentare CC - ppt','Callback','open prezentare.ppt');
   
   uimenu(f,'Label','Iesire','Callback','close',...
       'Separator','on','Accelerator','Q');
   
   uicontrol('Style','text',...
                   'Units','normalized',...
                   'String','TRANZISTOR BIPOLAR - CONEXIUNEA COLECTOR COMUN','FontSize',18,...
                   'foregroundcolor','black',...
                   'Background','w',...               
                   'Position',[0.3 0.7 0.4 0.1]);
               
                uicontrol('Style','Pushbutton',...
                   'Units','normalized',...
                   'String','Conexiunea colector comun',...
                   'foregroundcolor','black',...
                   'fontsize',12,...
                   'fontweight', 'bold',...
                   'Background','w',... 
                   'Position',[0.4 0.5 0.2 0.08],...
                   'Callback', 'start_interfata' );
               uicontrol('Style','Pushbutton',...
                   'Units','normalized',...
                   'String','Documentatie',...
                   'foregroundcolor','black',...
                   'fontsize',12,...
                   'fontweight', 'bold',...
                   'Background','w',... 
                   'Position',[0.4 0.4 0.2 0.08],...
                   'Callback', 'open(''documentatie.doc'')' );
                uicontrol('Style','Pushbutton',...
                   'Units','normalized',...
                   'String','Prezentare',...
                   'foregroundcolor','black',...
                   'fontsize',12,...
                   'fontweight', 'bold',...
                   'Background','w',... 
                   'Position',[0.4 0.3 0.2 0.08],...
                   'Callback','open(''prezentare.pptx'')' );
               
               
               
               
               